version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - weaviate
    environment:
      - WEAVIATE_HOST=http://weaviate:8080

  weaviate:
    image: semitechnologies/weaviate:1.22.3
    container_name: weaviate
    restart: always
    ports:
      - "8080:8080"
      - "50051:50051"
    environment:
      # change these depending on your setup
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - PERSISTENCE_DATA_PATH=/var/lib/weaviate
      - QUERY_DEFAULTS_LIMIT=25
      - ENABLE_MODULES=text2vec-openai
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data:

