version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5005:5005"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5005", "--reload"]

volumes:
  weaviate_data:

